# Generated by Django 3.2.3 on 2021-06-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='capacidad',
        ),
        migrations.CreateModel(
            name='TipoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('costo', models.FloatField()),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partido')),
                ('tipoAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoasiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadio'),
        ),
        migrations.CreateModel(
            name='ImagenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('altText', models.CharField(default='Imagen de Usuario', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('altText', models.CharField(default='Imagen de Usuario', max_length=200)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partido')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenEstadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('altText', models.CharField(default='Imagen de Estadio', max_length=200)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadio')),
            ],
        ),
    ]
