# Generated by Django 3.2.3 on 2021-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210609_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='descripción',
            field=models.TextField(default=''),
        ),
    ]
