# Generated by Django 3.2.4 on 2021-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estadio_descripción'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_espacios_reservados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
